name: Node.js Check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install
        run: corepack npm install
        working-directory: ./web
      - name: Build
        run: corepack npm run build
        working-directory: ./web
      - name: Type-check
        run: corepack npm run type-check
        working-directory: ./web
      - name: Lint
        run: corepack npm run lint
        working-directory: ./web
